//array departamentos y casas de campo//
const departamentos = [
    { id:1,
      direccion: "25 de mayo 610",
      precioDia: 6500,
      limpieza: true,
      habitaciones: 2,
      zona: "centro",
    },
    { id:2,
      direccion: "Entre rios 729",
      precioDia: 4500,
      limpieza: true,
      habitaciones: 2,
      zona: "centro",
    },
    { id:3,
      direccion: "Leguizamon 340",
      precioDia: 21000,
      limpieza: true,
      habitaciones: 3,
      zona: "centro",
    },
    { id:4,
      direccion: "Ituzaingo 999",
      precioDia: 3500,
      limpieza: false,
      habitaciones: 1,
      zona: "centro",
    },
    { id:5,
      direccion: "Pueyrredon 390",
      precioDia: 25000,
      limpieza: true,
      habitaciones: 2,
      zona: "centro",
    },
  ];
  const casasCampo = [
    { id:1,
      direccion: "San Martin 211",
      precioDia: 12500,
      limpieza: false,
      habitaciones: 3,
      zona: "rural",
      piscina: false,
    },
    {id:2,
      direccion: "Irigoyen 16",
      precioDia: 18500,
      limpieza: false,
      habitaciones: 5,
      zona: "rural",
      piscina: true,
    },
    {id:3,
      direccion: "Saavedra 36",
      precioDia: 30000,
      limpieza: false,
      habitaciones: 3,
      zona: "rural",
      piscina: true,
    },
    {id:4,
      direccion: "Belgran SN",
      precioDia: 6500,
      limpieza: false,
      habitaciones: 2,
      zona: "rural",
      piscina: false,
    },
    {id:5,
      direccion: "Mitre 346",
      precioDia: 21500,
      limpieza: false,
      habitaciones: 8,
      zona: "rural",
      piscina: true,
    },
  ];

  